version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - rag-service
    environment:
      - RAG_SERVICE_URL=http://rag-service:5000
  rag-service:
    build: ./rag-service
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
networks:
  default:
    driver: bridge